plugins {
    id 'com.android.application'
    id 'kotlin-android'
    id 'kotlin-parcelize'
    id 'kotlin-kapt'
    id 'androidx.navigation.safeargs.kotlin'
}

android {
    namespace = "com.ijikod.gmbn_youtube"
    compileSdk = 35

    defaultConfig {
        applicationId = "com.ijikod.gmbn_youtube"
        minSdk = 24
        targetSdk = 35
        versionCode = 1
        versionName = "1.0"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        release {
            minifyEnabled = false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }


    kotlinOptions {
        jvmTarget = "1.8"

        freeCompilerArgs += ["-opt-in=kotlin.RequiresOptIn"]
    }

    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_1_8
        targetCompatibility = JavaVersion.VERSION_1_8
    }

    buildFeatures {
        dataBinding = true
        viewBinding = true
    }
}

dependencies {
    implementation fileTree(dir: "libs", include: ["*.jar"])
    implementation (libs.androidx.core.ktx)
    implementation (libs.androidx.app.compat)
    implementation (libs.androidx.constraint.layout)
    implementation (libs.androidx.legacy.support)
    testImplementation (libs.junit)
    androidTestImplementation (libs.androidx.espresso.core)

    // architecture components
    implementation (libs.androidx.lifecycle.extensions)
    implementation (libs.androidx.lifecycle.runtime.ktx)
    implementation (libs.androidx.lifecycle.viewmodel.ktx)
    implementation (libs.androidx.lifecycle.livedate.ktx)
    implementation (libs.androidx.room.runtime)
    implementation (libs.androidx.room.ktx)
    implementation (libs.androidx.paging.runtime)
    implementation (libs.androidx.room.runtime)
    kapt (libs.androidc.room.compiler)

    // Navigation
    implementation (libs.androidx.fragment.navigation.ktx)
    implementation (libs.androidx.navigation.ui.ktx)

    //Retrofit
    implementation (libs.square.retrofit2)
    implementation (libs.square.retrofit2.gson.converter)
    implementation (libs.square.retrofit2.moshi.converter)

    //Glide
    implementation (libs.bumptech.glide)
    kapt (libs.bumptech.glide.compiler)

    // Assertions
    androidTestImplementation (libs.androidx.junit)
    androidTestImplementation (libs.androidx.test.truth)
    androidTestImplementation (libs.google.truth)

    // Espresso
    androidTestImplementation (libs.androidx.espresso.core)
    androidTestImplementation (libs.androidx.espresso.contrib)

    // AndroidJUnitRunner and JUnit Rules
    androidTestImplementation (libs.androidx.test.runner)
    androidTestImplementation (libs.androidx.test.rules)

    // Mockito
    androidTestImplementation (libs.mockito.core)
    androidTestImplementation (libs.mockito.android)
    androidTestImplementation (libs.androidx.arch.core)

    // Fragment
    implementation (libs.androidx.fragment.ktx)

    // Fragment Tests
    debugImplementation  (libs.androidx.fragment.testing)
}